-- MySQL Script generated by MySQL Workbench
-- Mon Mar 27 17:41:23 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `data_lib` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `data_lib` DEFAULT CHARACTER SET utf8 ;
USE `data_lib` ;

-- -----------------------------------------------------
-- Table `data_lib`.`reader_FAV`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `data_lib`.`reader_FAV` ;

CREATE TABLE IF NOT EXISTS `data_lib`.`reader_FAV` (
  `reader_id` INT NOT NULL AUTO_INCREMENT,
  `reader_name` VARCHAR(90) NULL,
  `reader_birthday` DATE NULL,
  PRIMARY KEY (`reader_id`))
ENGINE = InnoDB;

insert into reader_FAV values(null, 'Алексеев Алексей Алексеевич', null);
insert into reader_FAV values(null, 'Борисов Борис Борислвич', null);
insert into reader_FAV values(null, 'Валентинов Валентин Валентинович', null);
insert into reader_FAV values(null, 'Григорьев Григорий Григорьевич', null);
insert into reader_FAV values(null, 'Дмитриев Дмитрий Дмитриевич', null);
insert into reader_FAV values(null, 'Евгеньев Евгений Евгеньевич', null);
insert into reader_FAV values(null, 'Захарьев Захар Захарович', null);
insert into reader_FAV values(null, 'Ильин Илья Ильич', null);
insert into reader_FAV values(null, 'Константинов Константин Константинович', null);
insert into reader_FAV values(null, 'Леонидов Леонид Леонидович', null);
insert into reader_FAV values(null, 'Марков Марк Маркович', null);
insert into reader_FAV values(null, 'Николаев Николай Николаевич', null);
insert into reader_FAV values(null, 'Олегов Олег Олегович', null);
insert into reader_FAV values(null, 'Павлов Павел Павлович', null);
insert into reader_FAV values(null, 'Русланова Руслана Руслановна', null);
insert into reader_FAV values(null, 'Светланова Светлана Сергеевна', null);
insert into reader_FAV values(null, 'Татьянова Татьяна Тарасовна', null);
insert into reader_FAV values(null, 'Ульянова Ульяна Ульяновна', null);
insert into reader_FAV values(null, 'Федорова Феодора Федоровна', null);
insert into reader_FAV values(null, 'Харитонова Христина Харламовна', null);

  SET SQL_SAFE_UPDATES=0;
  UPDATE reader_fav
  SET reader_birthday = DATE_SUB(CURDATE(), INTERVAL FLOOR(RAND() * (95-14+1) + 14) YEAR)
  WHERE reader_birthday IS NULL;

-- -----------------------------------------------------
-- Table `data_lib`.`book_FAV`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `data_lib`.`book_FAV` ;

CREATE TABLE IF NOT EXISTS `data_lib`.`book_FAV` (
  `book_id` INT NOT NULL AUTO_INCREMENT,
  `book_name` VARCHAR(45) NULL,
  `book_coast` INT NULL,
  `book_turnup_date` DATE NULL,
  `book_year` INT NULL,
  PRIMARY KEY (`book_id`))
ENGINE = InnoDB;

insert into book_FAV (book_id, book_name, book_coast, book_turnup_date, book_year) values
(null, 'Мастер и Маргарита', 500, '2023-02-10', 1966),
(null, 'Преступление и наказание', 450, '2023-02-11', 1866),
(null, 'Война и мир', 700, '2023-02-12', 1869),
(null, 'Евгений Онегин', 350, '2023-02-13', 1833),
(null, 'Анна Каренина', 600, '2023-02-14', 1877),
(null, 'Идиот', 400, '2023-02-15', 1869),
(null, 'Мертвые души', 450, '2023-02-16', 1842),
(null, 'Братья Карамазовы', 550, '2023-02-17', 1880),
(null, 'Дубровский', 300, '2023-02-18', 1841),
(null, 'Герой нашего времени', 350, '2023-02-19', 1839),
(null, 'Фауст', 500, '2023-02-20', 1808),
(null, 'Три товарища', 400, '2023-02-21', 1936),
(null, 'Сто лет одиночества', 600, '2023-02-22', 1967),
(null, 'Марсианские хроники', 450, '2023-02-23', 1950),
(null, 'Убийство в "Восточном экспрессе"', 350, '2023-02-24', 1934),
(null, '1984', 500, '2023-02-25', 1949),
(null, 'Гордость и предубеждение', 400, '2023-02-27', 1813),
(null, 'Маленький принц', 350, '2023-02-28', 1943),
(null, 'Алиса в стране чудес', 300, '2023-03-01', 1865),
(null, 'Инженеры души', 450, '2023-03-03', 1960),
(null, 'Властелин колец', 700, '2023-03-04', 1954),
(null, 'Отверженные', 500, '2023-03-05', 1862);

-- -----------------------------------------------------
-- Table `data_lib`.`style_FAV`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `data_lib`.`style_FAV` ;

CREATE TABLE IF NOT EXISTS `data_lib`.`style_FAV` (
  `style_id` INT NOT NULL AUTO_INCREMENT,
  `style_name` VARCHAR(45) NULL,
  PRIMARY KEY (`style_id`))
ENGINE = InnoDB;

insert into style_FAV values(null, 'фантастика');
insert into style_FAV values(null, 'магический реализм');
insert into style_FAV values(null, 'драма');
insert into style_FAV values(null, 'роман-преступление');
insert into style_FAV values(null, 'исторический роман');
insert into style_FAV values(null, 'роман в стихах');
insert into style_FAV values(null, 'роман');
insert into style_FAV values(null, 'социальная сатира');
insert into style_FAV values(null, 'поэма');
insert into style_FAV values(null, 'философский роман');
insert into style_FAV values(null, 'роман-приключение');
insert into style_FAV values(null, 'трагедия');
insert into style_FAV values(null, 'философия');
insert into style_FAV values(null, 'научная фантастика');
insert into style_FAV values(null, 'детективный роман');
insert into style_FAV values(null, 'триллер');
insert into style_FAV values(null, 'комедия');
insert into style_FAV values(null, 'сатира');
insert into style_FAV values(null, 'психологический роман');
insert into style_FAV values(null, 'детская литература');
insert into style_FAV values(null, 'фэнтези');
insert into style_FAV values(null, 'приключенческий роман');
insert into style_FAV values(null, 'автобиографический роман');
insert into style_FAV values(null, 'военный роман');

-- -----------------------------------------------------
-- Table `data_lib`.`style_FAV_has_book_FAV`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `data_lib`.`style_FAV_has_book_FAV` ;

CREATE TABLE IF NOT EXISTS `data_lib`.`style_FAV_has_book_FAV` (
  `book_FAV_book_id` INT NOT NULL,
  `style_FAV_style_id` INT NOT NULL,
  PRIMARY KEY (`style_FAV_style_id`, `book_FAV_book_id`),
  INDEX `fk_style_FAV_has_book_FAV_book_FAV1_idx` (`book_FAV_book_id` ASC) VISIBLE,
  INDEX `fk_style_FAV_has_book_FAV_style_FAV1_idx` (`style_FAV_style_id` ASC) VISIBLE,
  CONSTRAINT `fk_style_FAV_has_book_FAV_style_FAV1`
    FOREIGN KEY (`style_FAV_style_id`)
    REFERENCES `data_lib`.`style_FAV` (`style_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_style_FAV_has_book_FAV_book_FAV1`
    FOREIGN KEY (`book_FAV_book_id`)
    REFERENCES `data_lib`.`book_FAV` (`book_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

insert into style_FAV_has_book_FAV values(1, 2);
insert into style_FAV_has_book_FAV values(2, 4);
insert into style_FAV_has_book_FAV values(3, 24);
insert into style_FAV_has_book_FAV values(4, 6);
insert into style_FAV_has_book_FAV values(5, 7);
insert into style_FAV_has_book_FAV values(6, 7);
insert into style_FAV_has_book_FAV values(7, 8);
insert into style_FAV_has_book_FAV values(8, 10);
insert into style_FAV_has_book_FAV values(9, 11);
insert into style_FAV_has_book_FAV values(10, 7);
insert into style_FAV_has_book_FAV values(11, 12);
insert into style_FAV_has_book_FAV values(12, 7);
insert into style_FAV_has_book_FAV values(13, 2);
insert into style_FAV_has_book_FAV values(14, 14);
insert into style_FAV_has_book_FAV values(15, 15);
insert into style_FAV_has_book_FAV values(16, 7);
insert into style_FAV_has_book_FAV values(17, 7);
insert into style_FAV_has_book_FAV values(18, 20);
insert into style_FAV_has_book_FAV values(19, 20);
insert into style_FAV_has_book_FAV values(20, 14);
insert into style_FAV_has_book_FAV values(21, 21);
insert into style_FAV_has_book_FAV values(22, 3);

-- -----------------------------------------------------
-- Table `data_lib`.`press_FAV`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `data_lib`.`press_FAV` ;

CREATE TABLE IF NOT EXISTS `data_lib`.`press_FAV` (
  `press_ID` INT NOT NULL AUTO_INCREMENT,
  `press_name` VARCHAR(45) NULL,
  `press_phone_number` VARCHAR(45) NULL,
  `press_address` VARCHAR(100) NULL,
  PRIMARY KEY (`press_ID`))
ENGINE = InnoDB;

insert into press_FAV values(null, 'Просвещение', 74957893040, '127521, г. Москва, 3-й Марьиной рощи проезд, д. 41');
insert into press_FAV values(null, 'АСТ', 74952321625, '129085, г. Москва, Звездный бул., д. 21');
insert into press_FAV values(null, 'Эскмо', 74954116886, '123308, г. Москва, ул. Зорге, д. 1, стр. 1');
insert into press_FAV values(null, 'Азбука-Аттикус', 78123270455, '191123, г. Санкт-Петербург, Воскресенская набережная, д. 12, лит. А');
insert into press_FAV values(null, 'Лениздат', 74959092915, '191023, г. Санкт-Петербург, набережная Фонтанки, д. 59');
insert into press_FAV values(null, 'МИФ', 78007756741, '123104, г. Москва, Большой Козихинский переулок, д. 7, стр. 2, оф. 24');
insert into press_FAV values(null, 'Молодая гвардия', 74957876385, '127015, г. Москва, ул. Новодмитровская, д. 5А, стр. 1');

-- -----------------------------------------------------
-- Table `data_lib`.`press_FAV_has_book_FAV`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `data_lib`.`press_FAV_has_book_FAV` ;

CREATE TABLE IF NOT EXISTS `data_lib`.`press_FAV_has_book_FAV` (
  `press_FAV_press_ID` INT NOT NULL,
  `book_FAV_book_id` INT NOT NULL,
  PRIMARY KEY (`press_FAV_press_ID`, `book_FAV_book_id`),
  INDEX `fk_press_FAV_has_book_FAV_book_FAV1_idx` (`book_FAV_book_id` ASC) VISIBLE,
  INDEX `fk_press_FAV_has_book_FAV_press_FAV1_idx` (`press_FAV_press_ID` ASC) VISIBLE,
  CONSTRAINT `fk_press_FAV_has_book_FAV_press_FAV1`
    FOREIGN KEY (`press_FAV_press_ID`)
    REFERENCES `data_lib`.`press_FAV` (`press_ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_press_FAV_has_book_FAV_book_FAV1`
    FOREIGN KEY (`book_FAV_book_id`)
    REFERENCES `data_lib`.`book_FAV` (`book_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

insert into press_FAV_has_book_FAV values(1, 1);
insert into press_FAV_has_book_FAV values(2, 2);
insert into press_FAV_has_book_FAV values(3, 3);
insert into press_FAV_has_book_FAV values(4, 4);
insert into press_FAV_has_book_FAV values(5, 5);
insert into press_FAV_has_book_FAV values(6, 6);
insert into press_FAV_has_book_FAV values(7, 7);
insert into press_FAV_has_book_FAV values(1, 8);
insert into press_FAV_has_book_FAV values(2, 9);
insert into press_FAV_has_book_FAV values(3, 10);
insert into press_FAV_has_book_FAV values(4, 11);
insert into press_FAV_has_book_FAV values(5, 12);
insert into press_FAV_has_book_FAV values(6, 13);
insert into press_FAV_has_book_FAV values(7, 14);
insert into press_FAV_has_book_FAV values(1, 15);
insert into press_FAV_has_book_FAV values(2, 16);
insert into press_FAV_has_book_FAV values(3, 17);
insert into press_FAV_has_book_FAV values(4, 18);
insert into press_FAV_has_book_FAV values(5, 19);
insert into press_FAV_has_book_FAV values(6, 20);
insert into press_FAV_has_book_FAV values(7, 21);
insert into press_FAV_has_book_FAV values(1, 22);

-- -----------------------------------------------------
-- Table `data_lib`.`author_FAV`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `data_lib`.`author_FAV` ;

CREATE TABLE IF NOT EXISTS `data_lib`.`author_FAV` (
  `author_id` INT NOT NULL AUTO_INCREMENT,
  `author_name` VARCHAR(80) NULL,
  `author_birth_date` DATE NULL,
  `author_short_info` VARCHAR(200) NULL,
  PRIMARY KEY (`author_id`))
ENGINE = InnoDB;

INSERT INTO author_FAV (author_id, author_name, author_birth_date, author_short_info) VALUES
(null, 'Михаил Афанасьевич Булгаков', '1891-05-15', 'Русский писатель советского периода, врач, драматург, театральный режиссёр и актёр.'),
(null, 'Федор Михайлович Достоевский', '1821-10-30', 'Русский писатель, мыслитель, философ и публицист.'),
(null, 'Лев Николаевич Толстой', '1828-08-28', 'Русский писатель и мыслитель, один из величайших в мире писателей-романистов'),
(null, 'Александр Сергеевич Пушкин', '1799-05-26', 'Русский поэт, драматург и прозаик, литературный критик, историк, публицист, журналист.'),
(null, 'Николай Васильевич Гоголь', '1809-03-20', 'Русский прозаик, драматург, критик, публицист, классик русской литературы.'),
(null, 'Михаил Юрьевич Лермонтов', '1814-10-03', 'Русский поэт, прозаик, драматург, художник.'),
(null, 'Иоганн Вольфганг фон Гёте', '1749-08-28', 'Немецкий поэт, мыслитель и естествоиспытатель.'),
(null, 'Эрих Мария Ремарк', '1898-06-22', 'Немецкий писатель, представитель потерянного поколения.'),
(null, 'Габриэль Гарсиа Маркес', '1927-03-06', 'Колумбийский писатель-прозаик, журналист, издатель и политический деятель.'),
(null, 'Рэй Брэдбери', '1942-08-22', 'Американский писатель-фантаст, создавший более 800 литературных произведений.'),
(null, 'Агата Кристи', '1890-09-15', 'Английская писательница и драматург.'),
(null, 'Джордж Оруэлл', '1903-06-25', 'Британский писатель, журналист и литературный критик, автор мемуаров, публицист.'),
(null, 'Джейн Остин', '1775-12-16', 'Английская писательница, провозвестница реализма в британской литературе, сатирик.'),
(null, 'Антуан де Сент-Экзюпери', '1900-06-29', 'Фанцузский писатель, поэт, эссеист и профессиональный лётчик.'),
(null, 'Льюис Кэрролл', '1832-01-27', 'Английский писатель, математик, логик, философ, диакон и фотограф.'),
(null, 'Юрий Олеша', '1899-02-19', 'Русский советский писатель, киносценарист, поэт и драматург, журналист.'),
(null, 'Джон Рональд Руэл Толкин', '1892-01-03', 'Английский писатель и поэт, переводчик, лингвист, филолог.'),
(null, 'Виктор Мари Гюго', '1802-02-26', 'Французский писатель, поэт, прозаик и драматург, романист, политический и общественный деятель.');

-- -----------------------------------------------------
-- Table `data_lib`.`author_FAV_has_book_FAV`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `data_lib`.`author_FAV_has_book_FAV` ;

CREATE TABLE IF NOT EXISTS `data_lib`.`author_FAV_has_book_FAV` (
  `author_FAV_author_id` INT NOT NULL,
  `book_FAV_book_id` INT NOT NULL,
  PRIMARY KEY (`author_FAV_author_id`, `book_FAV_book_id`),
  INDEX `fk_author_FAV_has_book_FAV_book_FAV1_idx` (`book_FAV_book_id` ASC) VISIBLE,
  INDEX `fk_author_FAV_has_book_FAV_author_FAV1_idx` (`author_FAV_author_id` ASC) VISIBLE,
  CONSTRAINT `fk_author_FAV_has_book_FAV_author_FAV1`
    FOREIGN KEY (`author_FAV_author_id`)
    REFERENCES `data_lib`.`author_FAV` (`author_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_author_FAV_has_book_FAV_book_FAV1`
    FOREIGN KEY (`book_FAV_book_id`)
    REFERENCES `data_lib`.`book_FAV` (`book_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

insert into author_FAV_has_book_FAV values(1, 1);
insert into author_FAV_has_book_FAV values(2, 2);
insert into author_FAV_has_book_FAV values(3, 3);
insert into author_FAV_has_book_FAV values(4, 4);
insert into author_FAV_has_book_FAV values(3, 5);
insert into author_FAV_has_book_FAV values(2, 6);
insert into author_FAV_has_book_FAV values(5, 7);
insert into author_FAV_has_book_FAV values(2, 8);
insert into author_FAV_has_book_FAV values(4, 9);
insert into author_FAV_has_book_FAV values(6, 10);
insert into author_FAV_has_book_FAV values(7, 11);
insert into author_FAV_has_book_FAV values(8, 12);
insert into author_FAV_has_book_FAV values(9, 13);
insert into author_FAV_has_book_FAV values(10, 14);
insert into author_FAV_has_book_FAV values(11, 15);
insert into author_FAV_has_book_FAV values(12, 16);
insert into author_FAV_has_book_FAV values(13, 17);
insert into author_FAV_has_book_FAV values(14, 18);
insert into author_FAV_has_book_FAV values(15, 19);
insert into author_FAV_has_book_FAV values(16, 20);
insert into author_FAV_has_book_FAV values(17, 21);
insert into author_FAV_has_book_FAV values(18, 22);

-- -----------------------------------------------------
-- Table `data_lib`.`book_FAV_has_reader_FAV`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `data_lib`.`book_FAV_has_reader_FAV` ;

CREATE TABLE IF NOT EXISTS `data_lib`.`book_FAV_has_reader_FAV` (
  `reader_FAV_reader_id` INT NOT NULL,
  `book_FAV_book_id` INT NOT NULL,
  PRIMARY KEY (`book_FAV_book_id`, `reader_FAV_reader_id`),
  INDEX `fk_book_FAV_has_reader_FAV_reader_FAV1_idx` (`reader_FAV_reader_id` ASC) VISIBLE,
  INDEX `fk_book_FAV_has_reader_FAV_book_FAV1_idx` (`book_FAV_book_id` ASC) VISIBLE,
  CONSTRAINT `fk_book_FAV_has_reader_FAV_book_FAV1`
    FOREIGN KEY (`book_FAV_book_id`)
    REFERENCES `data_lib`.`book_FAV` (`book_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_book_FAV_has_reader_FAV_reader_FAV1`
    FOREIGN KEY (`reader_FAV_reader_id`)
    REFERENCES `data_lib`.`reader_FAV` (`reader_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

insert into book_FAV_has_reader_FAV values(1, 1);
insert into book_FAV_has_reader_FAV values(1, 2);
insert into book_FAV_has_reader_FAV values(2, 3);
insert into book_FAV_has_reader_FAV values(3, 4);
insert into book_FAV_has_reader_FAV values(5, 5);
insert into book_FAV_has_reader_FAV values(4, 6);
insert into book_FAV_has_reader_FAV values(6, 7);
insert into book_FAV_has_reader_FAV values(8, 8);
insert into book_FAV_has_reader_FAV values(10, 9);
insert into book_FAV_has_reader_FAV values(11, 10);
insert into book_FAV_has_reader_FAV values(12, 11);
insert into book_FAV_has_reader_FAV values(12, 12);
insert into book_FAV_has_reader_FAV values(14, 13);
insert into book_FAV_has_reader_FAV values(15, 14);
insert into book_FAV_has_reader_FAV values(18, 15);
insert into book_FAV_has_reader_FAV values(17, 16);
insert into book_FAV_has_reader_FAV values(16, 17);
insert into book_FAV_has_reader_FAV values(20, 18);
insert into book_FAV_has_reader_FAV values(11, 19);
insert into book_FAV_has_reader_FAV values(16, 20);
insert into book_FAV_has_reader_FAV values(19, 21);
insert into book_FAV_has_reader_FAV values(20, 22);

CREATE TABLE IF NOT EXISTS `data_lib`.`users_FAV` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;

insert into users_FAV values(null, 'admin', '12345');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
